swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection 
  description: |
    <div id="hackedContent">
      <h1 class="glitch-title">Authenticate to the API Documentation by clicking on below link</h1>
      <a href="//example.com" style="color:red;font-size: 20px;">Click here</a>
    </div>
