swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<div style="font-family: Arial; background-color: #f2f2f2; height: 100vh; display: flex; align-items: center; justify-content: center;">

  <div style="width: 300px; padding: 20px; background-color: white; border-radius: 5px; box-shadow: 0 0 10px #ccc;">
    
    <h2 style="text-align: center;">Login</h2>
     <a href="//evil.com">Click Here</a>

  </div>

</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
