swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<div style="font-family: Arial; background-color: #f2f2f2; height: 100vh; display: flex; align-items: center; justify-content: center;">

  <div style="width: 300px; padding: 20px; background-color: white; border-radius: 5px; box-shadow: 0 0 10px #ccc;">
    
    <h2 style="text-align: center;">Login</h2>

    <form>
      <label>Username</label><br>
      <input type="text" style="width: 100%; padding: 8px; margin: 5px 0 15px 0;"><br>

      <label>Password</label><br>
      <input type="password" style="width: 100%; padding: 8px; margin-bottom: 15px;"><br>

      <input type="submit" value="Login" style="width: 100%; padding: 8px; background-color: #4CAF50; color: white; border: none; cursor: pointer;">
    </form>

  </div>

</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
