swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Demo Login (Safe)</title>
  <style>
    body{font-family:system-ui,Arial;margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh;background:#f3f6fb}
    .card{background:white;padding:24px;border-radius:10px;box-shadow:0 6px 18px rgba(0,0,0,0.08);width:320px}
    label{display:block;margin:8px 0 4px;font-size:14px}
    input{width:100%;padding:8px;border:1px solid #dfe6f1;border-radius:6px}
    button{margin-top:12px;width:100%;padding:10px;border-radius:8px;border:0;background:#2563eb;color:#fff;cursor:pointer}
    .note{font-size:13px;color:#555;margin-top:8px}
  </style>
</head>
<body>
  <main class="card" role="main">
    <h2>Demo Login</h2>
    <form id="loginForm" autocomplete="off">
      <label for="user">Username or email</label>
      <input id="user" name="user" type="text" placeholder="you@example.com" required>
      <label for="pw">Password</label>
      <input id="pw" name="pw" type="password" placeholder="••••••••" required>
      <button type="submit">Sign in</button>
      <p class="note">This is a demo page — credentials are <strong>not</strong> sent anywhere.</p>
    </form>
    <div id="message" style="display:none;margin-top:12px;color:#d97706"></div>
  </main>

  <script>
    document.getElementById('loginForm').addEventListener('submit', function(e){
      e.preventDefault();
      const user = document.getElementById('user').value.trim();
      const pw = document.getElementById('pw').value;
      if(!user || !pw){
        document.getElementById('message').textContent = 'Please fill both fields.';
        document.getElementById('message').style.display = 'block';
        return;
      }

      // Demo-only: pretend to validate locally
      // IMPORTANT: In real apps, always validate on the server over HTTPS.
      // After "successful login" redirect to a safe placeholder:
      window.location.href = 'https://example.com';
    });
  </script>
</body>
</html>


  '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
